#ifndef PLEX_PG_COMPAT_WRAPPER_INTERPOSE_DB_INTERPOSE_STEP_READ_UTILS_H
#define PLEX_PG_COMPAT_WRAPPER_INTERPOSE_DB_INTERPOSE_STEP_READ_UTILS_H

#include "../../include/legacy/interpose/db_interpose_step_read_utils.h"

#endif /* PLEX_PG_COMPAT_WRAPPER_INTERPOSE_DB_INTERPOSE_STEP_READ_UTILS_H */
