#ifndef PLEX_PG_COMPAT_WRAPPER_INTERPOSE_DB_INTERPOSE_TXN_UTILS_H
#define PLEX_PG_COMPAT_WRAPPER_INTERPOSE_DB_INTERPOSE_TXN_UTILS_H

#include "../../include/legacy/interpose/db_interpose_txn_utils.h"

#endif /* PLEX_PG_COMPAT_WRAPPER_INTERPOSE_DB_INTERPOSE_TXN_UTILS_H */
