#ifndef PLEX_PG_CORE_FFI_H
#define PLEX_PG_CORE_FFI_H

#pragma once

/* This file is generated by cbindgen. Do not edit directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct SqlTranslation {
  char *sql;
  char **param_names;
  int32_t param_count;
  int32_t success;
  uint8_t error[256];
} SqlTranslation;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern struct SqlTranslation sql_translate(const char *sqlite_sql);

extern void sql_translation_free(struct SqlTranslation *result);

extern void sql_translator_cleanup(void);

extern void sql_translator_free(char *ptr);

extern void sql_translator_init(void);

extern const char *sql_translator_last_error(void);

extern char *sql_translator_translate(const char *sql);

extern struct SqlTranslation sql_translator_translate_full(const char *sql);

extern void sql_translator_translation_free(struct SqlTranslation *t);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLEX_PG_CORE_FFI_H */
